site_name: AirBnB Scraping Analysis

theme: readthedocs

nav:
  - Scraping: "Scraping.md"
  - Cleaning: "Cleaning.md"
  - Visualizing: "Visualizing.md"
  - Predictive_Modeling: "Predictive_Modeling.md"
  - Dashboarding: "Dashboarding.md"
